name: Tag Versioner
run-name: Version Updating from Tags
on: [push]
jobs: 
  - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
  - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
  - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
  - name: tag-version
  uses: julesabr/tag-version@v1.5
